# Generated by Django 4.0.4 on 2022-04-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_of_post', models.AutoField(primary_key=True, serialize=False)),
                ('text_of_post', models.CharField(blank=True, max_length=400, null=True)),
                ('datetime_of_post', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleOfUser',
            fields=[
                ('id_of_role', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_role', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'role_of_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_of_status', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_status', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_of_user', models.AutoField(primary_key=True, serialize=False)),
                ('email_of_user', models.CharField(blank=True, max_length=70, null=True)),
                ('password_of_user', models.CharField(blank=True, max_length=250, null=True)),
                ('fio_of_user', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': '_user_',
                'managed': False,
            },
        ),
    ]
